name: sample_python_trigger

# on:
#   schedule:
#     - cron: '*/5 * * * *'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: run python script
        run: python main.py



